#%RAML 1.0
title: INSCRIBIRSE OFERTA EMPLEO
baseUri: localhost:8080/api/
mediaType: application/json
types:
  Demandante:
    description: Tipo de dato complejo para representar los datos de un demandante
    type: object
    properties:
      dni: string
      pass?: string
      nombre: string
      apellidos: string
      direccion: string
      poblacion: string
      telefono: string
      email: string
      fecha_nacimiento: string
      fecha_renovacion?: string
      iban: string
      situacion_laboral: boolean
      edad: integer
      titulos: string
      experiencia: integer
  Response:
    description: Tipo de dato complejo para representar una respuesta válida 
    type: object
    properties:
      estado: boolean
      mensaje: string
  Error:
    description: Tipo de dato complejo para representar una respuesta errónea
    type: object
    properties:
      codigo: integer
      mensaje: string
      
/procesoInscribirseOferta:
  description: proceso para inscribir un demandante de empleo en una oferta
  post:
    body:
    responses:
      201:
        body: 
          type: Response
          example: { "estado": true, "mensaje": "El demandante ha sido dado de alta en la oferta" }
      400:
        body: 
          type: Error
          example: { "codigo": 400, "mensaje": "Error al inscribirse en la oferta" }  