#%RAML 1.0
title: servicio lista candidatos
baseUri: localhost:8080/api/
mediaType: application/json
types:
  DatosListaCandidatos:
    description: Datos para lista candidatos
    properties: 
      dniDemandante:
        minLength: 0
        maxLength: 50
        type: string
      idOferta:
        minLength: 0
        maxLength: 50
        type: string
      puntuacion:
        minLength: 0
        maxLength: 50
        type: string
  ResponseDatosListaCandidatos:
    description: Tipo de dato complejo para representar una respuesta válida
    properties:
      estado: boolean
      mensaje:
        minLength: 0
        maxLength: 50
        type: string
  ErrorDatosListaCandidatos:
    description: Tipo de dato complejo para representar una respuesta errónea
    type: object
    properties:
      codigo: integer
      mensaje:
        minLength: 0
        maxLength: 50
        type: string
      
/listaCandidatos:
  description: proceso para inscribir un demandante de empleo en una oferta
  post:
    body:
      type: DatosListaCandidatos
      example: {"dniDemandante" : "48628778E", "idOferta": "2", "puntuacion":"0"}
    responses:
      201:
        body: 
          type: ResponseDatosListaCandidatos
          example: { "estado": true, "mensaje": "Se ha inscrito en la lista de candidatos" }
      400:
        body: 
          type: ErrorDatosListaCandidatos
          example: { "codigo": 400, "mensaje": "Error al inscribirse en la lista" }
  put:
    body:
      type: DatosListaCandidatos
      example: {"dniDemandante" : "48628778E", "idOferta": "2", "puntuacion":"0"}
    responses:
      201:
        body: 
          type: ResponseDatosListaCandidatos
          example: { "estado": true, "mensaje": "Se ha actualizado en la lista de candidatos" }
      400:
        body: 
          type: ErrorDatosListaCandidatos
          example: { "codigo": 400, "mensaje": "Error al actualizar en la lista" }
