// Template: Base Controller (ApiControllerBase.t4) version 5.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using ServiciosRest.ListaCandidatos.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace ServiciosRest.ListaCandidatos
{
    [RoutePrefix("listaCandidatos")]
    public partial class ListaCandidatosController : ApiController
    {


/// <summary>
		/// proceso para inscribir un demandante de empleo en una oferta - /listaCandidatos
		/// </summary>
		/// <param name="datosListaCandidatos">Datos para lista candidatos</param>
		/// <returns>MultipleListaCandidatosPost</returns>
        [ResponseType(typeof(MultipleListaCandidatosPost))]
        [HttpPost]
        [Route("listaCandidatos")]
        public virtual IHttpActionResult PostBase([FromBody] ServiciosRest.ListaCandidatos.Models.DatosListaCandidatos datosListaCandidatos)
        {
            // Do not modify this code
                        return  ((IListaCandidatosController)this).Post(datosListaCandidatos);
                    }

/// <summary>
		/// proceso para inscribir un demandante de empleo en una oferta - /listaCandidatos
		/// </summary>
		/// <param name="tipoAsignarPuntuacion">Tipo de datos que contiene un demandante y una oferta</param>
		/// <returns>MultipleListaCandidatosPut</returns>
        [ResponseType(typeof(MultipleListaCandidatosPut))]
        [HttpPut]
        [Route("listaCandidatos")]
        public virtual IHttpActionResult PutBase([FromBody] ServiciosRest.ListaCandidatos.Models.TipoAsignarPuntuacion tipoAsignarPuntuacion)
        {
            // Do not modify this code
                        return  ((IListaCandidatosController)this).Put(tipoAsignarPuntuacion);
                    }
    }
}
