#%RAML 1.0
title: servicio lista candidatos
baseUri: localhost:8080/api/
mediaType: application/json
types:
  DatosListaCandidatos:
    description: Datos para lista candidatos
    properties: 
      dniDemandante:
        minLength: 0
        maxLength: 50
        type: string
      idOferta:
        minLength: 0
        maxLength: 50
        type: string
      puntuacion:
        minLength: 0
        maxLength: 50
        type: string
  ResponseDatosListaCandidatos:
    description: Tipo de dato complejo para representar una respuesta válida
    properties:
      estado: boolean
      mensaje:
        minLength: 0
        maxLength: 50
        type: string
  ErrorDatosListaCandidatos:
    description: Tipo de dato complejo para representar una respuesta errónea
    type: object
    properties:
      codigo: integer
      mensaje:
        minLength: 0
        maxLength: 50
        type: string
  TipoAsignarPuntuacion:
    description: Tipo de datos que contiene un demandante y una oferta
    properties:
       demand_dni: 
        minLength: 0
        maxLength: 50
        type: string
       demand_edad: 
        minLength: 0
        maxLength: 50
        type: string
       demand_titulos: 
        minLength: 0
        maxLength: 50
        type: string
       demand_experiencia: 
        minLength: 0
        maxLength: 50
        type: string
       ofert_id: 
        minLength: 0
        maxLength: 50
        type: string
       ofert_edad: 
        minLength: 0
        maxLength: 50
        type: string
       ofert_titulos: 
        minLength: 0
        maxLength: 50
        type: string
       ofert_experiencia:
        minLength: 0
        maxLength: 50
        type: string
      
/listaCandidatos:
  description: proceso para inscribir un demandante de empleo en una oferta
  post:
    body:
      type: DatosListaCandidatos
      example: {"dniDemandante" : "48628778E", "idOferta": "2", "puntuacion":"0"}
    responses:
      201:
        body: 
          type: ResponseDatosListaCandidatos
          example: { "estado": true, "mensaje": "Se ha inscrito en la lista de candidatos" }
      400:
        body: 
          type: ErrorDatosListaCandidatos
          example: { "codigo": 400, "mensaje": "Error al inscribirse en la lista" }
  put:
    body:
      application/json:    
       type: TipoAsignarPuntuacion
       example: 
        { 
          "demand_dni": "48628778R", 
          "demand_edad": "75", 
          "demand_titulos": "grado universitario", 
          "demand_experiencia": "2", 
          "ofert_id": "1", 
          "ofert_edad": "25", 
          "ofert_titulos": "grado universitario", 
          "ofert_experiencia": "2" 
        }
    responses:
      201:
        body: 
          type: ResponseDatosListaCandidatos
          example: { "estado": true, "mensaje": "Se ha actualizado en la lista de candidatos" }
      400:
        body: 
          type: ErrorDatosListaCandidatos
          example: { "codigo": 400, "mensaje": "Error al actualizar en la lista" }
