// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServiciosRest.Demandantes.Models
{
    /// <summary>
    /// Multiple Response Types Demandante, Error
    /// </summary>
    public partial class MultipleDemandanteDniGet
    {
        

        /// <summary>
        ///  Tipo de dato complejo para representar los datos de un demandante
        /// </summary>

        public Demandante Demandante { get; set; }

        /// <summary>
        ///  Tipo de dato complejo para representar una respuesta errónea
        /// </summary>

        public Error Error { get; set; }
    } // end class

} // end Models namespace

