// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServiciosRest.ListaCandidatos.Models
{
    /// <summary>
    /// Multiple Response Types ResponseDatosListaCandidatos, ErrorDatosListaCandidatos
    /// </summary>
    public partial class MultipleListaCandidatosPut
    {
        

        /// <summary>
        ///  Tipo de dato complejo para representar una respuesta válida
        /// </summary>

        public ResponseDatosListaCandidatos ResponseDatosListaCandidatos { get; set; }

        /// <summary>
        ///  Tipo de dato complejo para representar una respuesta errónea
        /// </summary>

        public ErrorDatosListaCandidatos ErrorDatosListaCandidatos { get; set; }
    } // end class

} // end Models namespace

