// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServiciosRest.Oferta.Models
{
    /// <summary>
    /// Multiple Response Types Requisitos, ErrorOferta
    /// </summary>
    public partial class MultipleOfertaIdRequisitosGet
    {
        

        /// <summary>
        ///  requisitos de una oferta
        /// </summary>

        public Requisitos Requisitos { get; set; }

        /// <summary>
        ///  Tipo de dato complejo para representar una respuesta errónea
        /// </summary>

        public ErrorOferta ErrorOferta { get; set; }
    } // end class

} // end Models namespace

