// Template: Base Controller (ApiControllerBase.t4) version 5.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using ServiciosRest.Oferta.Models;

// Do not modify this file. This code was generated by AMF Server Scaffolder

namespace ServiciosRest.Oferta
{
    [RoutePrefix("oferta/{id}/requisitos")]
    public partial class OfertaIdRequisitosController : ApiController
    {


/// <summary>
		/// obtener requisitos de una oferta, la experiencia es en años - /oferta/{id}/requisitos
		/// </summary>
		/// <param name="Id"></param>
		/// <returns>MultipleOfertaIdRequisitosGet</returns>
        [ResponseType(typeof(MultipleOfertaIdRequisitosGet))]
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase([FromUri] string Id)
        {
            // Do not modify this code
                        return  ((IOfertaIdRequisitosController)this).Get(Id);
                    }
    }
}
