// Template: Models (ApiModel.t4) version 5.0

// This code was generated by AMF Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ServiciosRest.ListaCandidatos.Models
{
    /// <summary>
    /// Tipo de dato complejo para representar una respuesta válida
    /// </summary>
    public partial class ResponseDatosListaCandidatos
    {
        

        [Required]
        [MaxLength(0)]
        [MinLength(0)]
		[JsonProperty("estado")]
        public bool Estado { get; set; }

        [Required]
        [MaxLength(50)]
        [MinLength(0)]
		[JsonProperty("mensaje")]
        public string Mensaje { get; set; }
    } // end class

} // end Models namespace

